version: "1"
rules:
  - base: main
    upstream: kedacore:main
    mergeMethod: hardreset
    conflictReviewers:      # On merge conflict assign a reviewer
      - robsondepaula
  - base: v1
    upstream: kedacore:v1
    mergeMethod: hardreset
    conflictReviewers:
      - robsondepaula